name: CI
on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"
env:
  CEF_VERSION: "136.1.6+g1ac1b14+chromium-136.0.7103.114"

jobs:
  test:
    name: Test
    # if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            run_on: macos-latest
          - target: x86_64-linux-gnu
            run_on: ubuntu-latest
          - target: x86_64-windows-msvc
            run_on: windows-latest
    runs-on: ${{ matrix.run_on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install system dependencies
        if: ${{ matrix.run_on != 'windows-latest' }}
        run: script/bootstrap
      - name: Machete
        if: ${{ matrix.run_on == 'macos-latest' }}
        uses: bnjbvr/cargo-machete@main
      - name: Setup | Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: test-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache CEF
        id: cache-cef
        uses: actions/cache@v4
        with:
          path: $HOME/.cef
          key: cef-${{ env.CEF_VERSION }}-${{ matrix.target }}
      - name: Typo check
        if: ${{ matrix.run_on == 'macos-latest' }}
        run: |
          cargo install typos-cli || echo "typos-cli already installed"
          typos
      - name: Lint
        if: ${{ matrix.run_on == 'macos-latest' }}
        run: |
          cargo clippy -- --deny warnings
      - name: Test
        run: |
          cargo test --workspace --exclude wef --exclude gpui-webview


  test-wef:
    name: Test Wef
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            run_on: macos-latest
          - target: x86_64-linux-gnu
            run_on: ubuntu-latest
          - target: x86_64-windows-msvc
            run_on: windows-latest
    runs-on: ${{ matrix.run_on }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for crate changes
        uses: dorny/paths-filter@v2
        id: crates-changes
        with:
          filters: |
            wef:
              - 'crates/wef/**'
            webview:
              - 'crates/webview/**'

      - name: Skip if no crate changes
        if: steps.crates-changes.outputs.wef != 'true' && steps.crates-changes.outputs.webview != 'true'
        run: echo "No changes in wef or gpui-webview crates, skipping tests"

      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install system dependencies
        run: script/bootstrap
      - name: Setup | Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: test-crates-cargo-${{ matrix.target }}-wef-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache CEF
        id: cache-cef
        uses: actions/cache@v4
        with:
          path: $HOME/.cef
          key: cef-${{ env.CEF_VERSION }}-${{ matrix.target }}
      - name: Init CEF
        run: |
          cargo run -p cargo-wef -- wef init

      - name: Test Wef Linux
        if: matrix.run_on == 'ubuntu-latest'
        run: |
          cargo run -p cargo-wef wef add-framework target/debug
          cargo test -p wef
          cargo test -p gpui-webview

      - name: Test Wef Windows
        if: matrix.run_on == 'windows-latest'
        run: |
          cargo run -p cargo-wef wef add-framework target/debug
          cargo test -p wef
          cargo test -p gpui-webview

      - name: Test Wef MacOS
        if: matrix.run_on == 'macos-latest'
        run: |
          cargo test -p wef
          cargo test -p gpui-webview
